version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    image: fastapi_celery_example_web
    # '/start' is the shell script to run the service
    command: /start
    # this  volumne is used to map the files and folders on the host to the container
    # so if w e change code on hte host, code in the docker container will be updated
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env/.dev-sample
    depends_on:
      - redis
      - db
  
  db:
    image: postgres:alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env/.dev-sample
  
  redis:
    image: redis:6-alpine
  
  celery_worker:
    build: 
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    image: fastapi_celery_example_celery_worker
    command: /start-celeryworker
    volumes:
      - .:/app
    env_file:
      - .env/.dev-sample
    depends_on:
      - db
      - redis

  celery_beat:
    build: 
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    image: fastapi_celery_example_celery_beat
    command: /start-celerybeat
    volumes:
      - .:/app
    env_file:
      - .env/.dev-sample
    depends_on:
      - redis
      - db
    
  flower:
    build: 
      context: .
      dockerfile: ./compose/local/fastapi/Dockerfile
    image: fastapi_celery_example_flower
    command: /start-flower
    volumes:
      - .:/app
    env_file:
      - .env/.dev-sample
    ports:
      - 5557:5555
    depends_on:
      - redis
      - db


volumes:
  postgres_data: